version: '1'
services:
  streamlit:
    image: mittal15/streamlit_researchub:v1.0
    ports:
      - "8000:8000"
    env_file:
      - .env
  fastapi:
    image: mittal15/fastapi_researchub:v1.0
    ports:
      - "8090:8090"
    env_file:
      - .env